-- Coord.luau
loadstring(game:HttpGet("https://raw.githubusercontent.com/WallScripts/tool/refs/heads/main/Coord.luau"))()

-- Esp.luau
loadstring(game:HttpGet("https://raw.githubusercontent.com/WallScripts/tool/refs/heads/main/Esp.luau"))()

-- Fullbright.luau
loadstring(game:HttpGet("https://raw.githubusercontent.com/WallScripts/tool/refs/heads/main/Fullbright.luau"))()

-- Noclip.luau
loadstring(game:HttpGet("https://raw.githubusercontent.com/WallScripts/tool/refs/heads/main/Noclip.luau"))()

-- Speed.luau
loadstring(game:HttpGet("https://raw.githubusercontent.com/WallScripts/tool/refs/heads/main/Speed.luau"))()

-- Swim.luau
loadstring(game:HttpGet("https://raw.githubusercontent.com/WallScripts/tool/refs/heads/main/Swim.luau"))()

-- Tp.luau
loadstring(game:HttpGet("https://raw.githubusercontent.com/WallScripts/tool/refs/heads/main/Tp.luau"))()

-- Xray.luau
loadstring(game:HttpGet("https://raw.githubusercontent.com/WallScripts/tool/refs/heads/main/Xray.luau"))()
